### ISSUE TITLE
99_miscellaneous.playground 가 열리지 않습니다.

### ISSUE THREAD

**Issue by mohok** [kimjj81/SwiftWorkshopAlpha#1]
아이패드 프로 12.9 2세대에서 
99_miscellaneous.playground 가 열리지 않았습니다.

패키지 내용 보기 - page 폴더의 
잡다한용어.xcplaygroundpage  의 파일명을 영어로 바꿔서 해결하였습니다~

**Comment by kimjj81** [comment]
감사합니다. 해당 내역 반영했습니다.
